services:
  postgresql:
    container_name: postgresql
    restart: unless-stopped
    image: postgres:latest
    build:
      context: .
      dockerfile: PostgresDockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  adesso-api:
    container_name: adesso-api
    restart: unless-stopped
    image: adesso-api
    build:
      context: .
      dockerfile: ./Adesso.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Port=5432;Database=adesso_dev;User Id=postgres;Password=admin;
      - ConnectionStrings__ReadOnlyConnection=Server=host.docker.internal;Port=5432;Database=adesso_dev;User Id=postgres;Password=admin;
    depends_on:
      - postgresql